services:
  timelog.storage.default: "@timelog.storage.file"

  timelog.repository.activity:
    class: \TonyPiper\TimeLog\Repository\ActivityRepository
    arguments: ["@timelog.storage.default"]

  timelog.service.filesystem:
    class: \Symfony\Component\Filesystem\Filesystem

  timelog.storage.file:
    class: \TonyPiper\TimeLog\Storage\FileStorage
    arguments: ["@timelog.service.filesystem", "%file_path%"]

  timelog.command.report.basic:
    class: \TonyPiper\TimeLog\Console\Command\BasicReportCommand
    arguments: ["@timelog.repository.activity", "@timelog.report_builder.basic"]
    tags:
                -  { name: console.command }

  timelog.command.report.grouped:
    class: \TonyPiper\TimeLog\Console\Command\GroupedReportCommand
    arguments: ["@timelog.repository.activity", "@timelog.report_builder.grouped"]
    tags:
                -  { name: console.command }

  timelog.command.log:
    class: \TonyPiper\TimeLog\Console\Command\LogCommand
    arguments: ["@timelog.repository.activity"]
    tags:
                -  { name: console.command }

  timelog.command.edit:
    class: \TonyPiper\TimeLog\Console\Command\EditCommand
    arguments: ["@timelog.storage.default"]
    tags:
                -  { name: console.command }

  timelog.command.update:
    class: \TonyPiper\TimeLog\Console\Command\UpdateCommand
    tags:
                -  { name: console.command }

  timelog.twig.extension.filter.report:
    class: \TonyPiper\TimeLog\Twig\Extension\ReportFilterExtension
    arguments: ["%filters%"]

  timelog.report_builder.basic:
    class: \TonyPiper\TimeLog\Report\Builder\BasicReportBuilder
    arguments: ["@timelog.twig.extension.filter.report"]

  timelog.report_builder.grouped:
    class: \TonyPiper\TimeLog\Report\Builder\GroupedReportBuilder
    arguments: ["@timelog.twig.extension.filter.report"]

